sudo: required
language: generic
services:
    - docker

before_install:
  - docker build -t tjabane/react-test -f ./client/Dockerfile.dev ./client

script:
  docker run -e CI=true tjabane/react-test npm run test -- --coverage

after_success:
  - docker build -t tjabane/multi-react ./client
  - docker build -t tjabane/multi-nginx ./nginx
  - docker build -t tjabane/multi-server ./server
  - docker build -t tjabane/multi-worker ./worker

  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  docker push tjabane/multi-react
  docker push tjabane/multi-nginx
  docker push tjabane/multi-server
  docker push tjabane/multi-worker
